version : '3.1'

services:

    mongodb:
        image: mongo
        container_name: mongodb
        hostname: mongodb
        restart: always
        volumes:
            - ~/mongo-volume:/data/db
        ports:
            - 27017:27017
        environment:
             MONGO_INITDB_ROOT_USERNAME: jadca
             MONGO_INITDB_ROOT_PASSWORD: 123456
    
    mongodb-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb 
            ME_CONFIG_MONGODB_ADMINUSERNAME: jadca
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

